### ISSUE TITLE
[Document] Open API Specification

### ISSUE THREAD

**Issue by hyeneung** [hyeneung/tech-blog-hub-site#13]
## Work Details
- Create a comprehensive OpenAPI Specification (OAS) document to define and describe our tech blog hub site API.

## Task List
- [x] Define basic API info (title, version, description)
- [x] List and describe all API endpoints
- [x] Define request/response schemas for each endpoint
