### ISSUE TITLE
[Feature] text handler

### ISSUE THREAD

**Issue by hyeneung** [hyeneung/tech-blog-hub-site#2]
## Work Details
- implement text handler
  - return analyzed text data to the gRPC client(crawler)
## Task List
- [x] write gRPC server code
- [x] study asynchronous programming library in python and apply
- [x] create a mock function to return summarized text and other data
- [x] test performance with sending large text data
