### ISSUE TITLE
[Feature] API server program

### ISSUE THREAD

**Issue by hyeneung** [hyeneung/tech-blog-hub-site#6]
## Work Details
- develop API server program

## Task List
- [x] define API specifications
- [x] implement API for tech-blog-hub-site
- [x] validate user input
- [ ] implement API for Chrome Extension
